- hosts: localhost
  become: true
  pre_tasks:
    - name: Update cache
      apt:
        update_cache: true
      tags:
      - node
      - Zsh

  tasks:
    - include: task/zsh.yaml
    - include: task/node.yaml